version: "3.8"
services:
    nginx:
        build:
            context: ./
            dockerfile : Dockerfile
        container_name: nginx-server
        restart: always
        ports:
            - 8081:80
        volumes:
            - ./html:/usr/share/nginx/html/

networks:
    default:
        external:
            name: goldengateNet
volumes:
    html: {}
