version: "2.0"
services:
    nginx:
        build:
            context: ./
            dockerfile : Dockerfile
        container_name: nginx-server
        restart: always
        ports:
            - 8081:80

        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: "3"
               
        volumes:
            - ./html:/usr/share/nginx/html/

networks:
    default:
        external:
            name: goldengateNet
volumes:
    html: {}
